# Generated by Django 6.0.3 on 2026-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_content_lesson_materials_url_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='exercises',
            field=models.TextField(blank=True, default=''),
        ),
    ]
