# Generated by Django 6.0.3 on 2026-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_add_lesson_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='workload',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
