# Generated by Django 6.0.3 on 2026-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_add_course_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dance_style',
            field=models.CharField(blank=True, choices=[('ballet', 'Ballet'), ('samba', 'Samba'), ('forro', 'Forró'), ('hip_hop', 'Hip-Hop'), ('contemporaneo', 'Contemporâneo'), ('funk', 'Funk'), ('jazz', 'Jazz'), ('salão', 'Dança de Salão'), ('outras', 'Outras')], default='', max_length=20),
        ),
    ]
